# Generated by Django 5.0.6 on 2024-08-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='address_2',
            new_name='address2',
        ),
    ]
